"""Add title and tags to generated_images

Revision ID: 02794a7298bd
Revises: 3cc5ed08a974
Create Date: 2025-09-16 13:19:09.855113

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "02794a7298bd"
down_revision: str | Sequence[str] | None = "3cc5ed08a974"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generated_images", sa.Column("title", sa.String(length=255), nullable=True))
    op.add_column("generated_images", sa.Column("tags", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_images", "tags")
    op.drop_column("generated_images", "title")
    # ### end Alembic commands ###
