"""add_lyric_parsing_rules_table

Revision ID: 0f864573b58a
Revises: e57e0e47507a
Create Date: 2025-10-17 13:08:39.734117

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0f864573b58a"
down_revision: str | Sequence[str] | None = "e57e0e47507a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lyric_parsing_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("replacement", sa.Text(), nullable=False),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lyric_parsing_rules_active"), "lyric_parsing_rules", ["active"], unique=False)
    op.create_index(op.f("ix_lyric_parsing_rules_order"), "lyric_parsing_rules", ["order"], unique=False)
    op.create_index(op.f("ix_lyric_parsing_rules_rule_type"), "lyric_parsing_rules", ["rule_type"], unique=False)
    # ### end Alembic commands ###

    # Insert default cleanup rules (migrated from hardcoded logic in lyric-creation.component.ts)
    op.execute("""
        INSERT INTO lyric_parsing_rules (name, description, pattern, replacement, rule_type, active, "order")
        VALUES
        ('Remove Trailing Spaces', 'Remove whitespace at the end of each line', '\\s+$', '', 'cleanup', true, 1),
        ('Normalize Smart Quotes (Double)', 'Convert curly double quotes to straight quotes', '[\\u201C\\u201D]', '"', 'cleanup', true, 2),
        ('Normalize Smart Quotes (Single)', 'Convert curly single quotes to straight quotes', '[\\u2018\\u2019]', '''', 'cleanup', true, 3),
        ('Normalize Em Dash', 'Convert em dash to regular dash with spaces', '\\u2014', ' - ', 'cleanup', true, 4),
        ('Normalize En Dash', 'Convert en dash to regular dash with spaces', '\\u2013', ' - ', 'cleanup', true, 5),
        ('Normalize Ellipsis', 'Convert ellipsis character to three periods', '\\u2026', '...', 'cleanup', true, 6),
        ('Line Break After Comma + Capital', 'Add line break after comma when followed by capital letter', ',\\s+(?=[A-Z])', ',\\n', 'cleanup', true, 7),
        ('Line Break After Period + Capital', 'Add line break after period when followed by capital letter', '\\.\\s+(?=[A-Z])', '.\\n', 'cleanup', true, 8),
        ('Reduce Blank Lines', 'Remove excessive blank lines (max 1 blank line)', '\\n{3,}', '\\n\\n', 'cleanup', true, 9)
    """)

    # Insert default section detection rule
    op.execute("""
        INSERT INTO lyric_parsing_rules (name, description, pattern, replacement, rule_type, active, "order")
        VALUES
        ('Section Label Detection', 'Detect Markdown-style section labels (Intro, Verse, Chorus, etc.)', '^\\*\\*\\s*(Intro|Verse\\s*\\d+|Chorus|Bridge|Outro|Pre[-_\\s]?chorus|Post[-_\\s]?chorus)\\s*\\*\\*$', '', 'section', true, 1)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lyric_parsing_rules_rule_type"), table_name="lyric_parsing_rules")
    op.drop_index(op.f("ix_lyric_parsing_rules_order"), table_name="lyric_parsing_rules")
    op.drop_index(op.f("ix_lyric_parsing_rules_active"), table_name="lyric_parsing_rules")
    op.drop_table("lyric_parsing_rules")
    # ### end Alembic commands ###
