"""Fix song_releases.updated_at NOT NULL constraint

Revision ID: abe5d41256e3
Revises: 28fe232c9ffd
Create Date: 2025-11-10 08:03:07.509226

CRITICAL FIX: song_releases.updated_at was NOT NULL but had no server_default,
causing INSERT failures. Added server_default=now() to match created_at behavior.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "abe5d41256e3"
down_revision: str | Sequence[str] | None = "28fe232c9ffd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_costs_monthly_provider_year_month"), table_name="api_costs_monthly")
    op.drop_constraint(op.f("uq_provider_org_year_month"), "api_costs_monthly", type_="unique")
    op.alter_column("generated_images", "prompt", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "project_files", "file_size_bytes", existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True
    )
    op.alter_column(
        "project_files",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_files",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_project_files_project"), table_name="project_files")
    op.drop_index(op.f("idx_project_files_s3_key"), table_name="project_files")
    op.drop_index(op.f("ix_project_files_file_hash"), table_name="project_files")
    op.create_index(op.f("ix_project_files_folder_id"), "project_files", ["folder_id"], unique=False)
    op.create_index(op.f("ix_project_files_id"), "project_files", ["id"], unique=False)
    op.create_index(op.f("ix_project_files_project_id"), "project_files", ["project_id"], unique=False)
    op.create_index(op.f("ix_project_files_s3_key"), "project_files", ["s3_key"], unique=False)
    op.alter_column(
        "project_folders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_project_folders_project"), table_name="project_folders")
    op.create_index(op.f("ix_project_folders_id"), "project_folders", ["id"], unique=False)
    op.create_index(op.f("ix_project_folders_project_id"), "project_folders", ["project_id"], unique=False)
    op.alter_column(
        "project_image_references",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("uq_project_image"), "project_image_references", type_="unique")
    op.drop_constraint(op.f("uq_prompt_category_action"), "prompt_templates", type_="unique")
    op.alter_column(
        "release_project_references",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("uq_release_project"), "release_project_references", type_="unique")
    op.alter_column(
        "song_projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "song_projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_song_projects_tags"), table_name="song_projects", postgresql_using="gin")
    op.drop_index(op.f("idx_song_projects_user"), table_name="song_projects")
    op.drop_index(
        op.f("ix_song_projects_project_name_gin"),
        table_name="song_projects",
        postgresql_ops={"project_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_song_projects_id"), "song_projects", ["id"], unique=False)
    op.create_index(op.f("ix_song_projects_user_id"), "song_projects", ["user_id"], unique=False)
    # Fix song_releases.updated_at: Add server_default for INSERT
    op.alter_column(
        "song_releases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "song_releases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_song_releases_id"), "song_releases", ["id"], unique=False)
    op.drop_index(op.f("idx_sketches_project"), table_name="song_sketches")
    op.create_index(op.f("ix_song_sketches_project_id"), "song_sketches", ["project_id"], unique=False)
    op.drop_index(op.f("idx_songs_project"), table_name="songs")
    op.create_index(op.f("ix_songs_project_id"), "songs", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_songs_project_id"), table_name="songs")
    op.create_index(op.f("idx_songs_project"), "songs", ["project_id"], unique=False)
    op.drop_index(op.f("ix_song_sketches_project_id"), table_name="song_sketches")
    op.create_index(op.f("idx_sketches_project"), "song_sketches", ["project_id"], unique=False)
    op.drop_index(op.f("ix_song_releases_id"), table_name="song_releases")
    op.alter_column(
        "song_releases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "song_releases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_song_projects_user_id"), table_name="song_projects")
    op.drop_index(op.f("ix_song_projects_id"), table_name="song_projects")
    op.create_index(
        op.f("ix_song_projects_project_name_gin"),
        "song_projects",
        ["project_name"],
        unique=False,
        postgresql_ops={"project_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_song_projects_user"), "song_projects", ["user_id"], unique=False)
    op.create_index(op.f("idx_song_projects_tags"), "song_projects", ["tags"], unique=False, postgresql_using="gin")
    op.alter_column(
        "song_projects",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "song_projects",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint(
        op.f("uq_release_project"),
        "release_project_references",
        ["release_id", "project_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "release_project_references",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint(
        op.f("uq_prompt_category_action"),
        "prompt_templates",
        ["category", "action"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_project_image"),
        "project_image_references",
        ["project_id", "image_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "project_image_references",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_project_folders_project_id"), table_name="project_folders")
    op.drop_index(op.f("ix_project_folders_id"), table_name="project_folders")
    op.create_index(op.f("idx_project_folders_project"), "project_folders", ["project_id"], unique=False)
    op.alter_column(
        "project_folders",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_project_files_s3_key"), table_name="project_files")
    op.drop_index(op.f("ix_project_files_project_id"), table_name="project_files")
    op.drop_index(op.f("ix_project_files_id"), table_name="project_files")
    op.drop_index(op.f("ix_project_files_folder_id"), table_name="project_files")
    op.create_index(op.f("ix_project_files_file_hash"), "project_files", ["file_hash"], unique=False)
    op.create_index(op.f("idx_project_files_s3_key"), "project_files", ["s3_key"], unique=False)
    op.create_index(op.f("idx_project_files_project"), "project_files", ["project_id"], unique=False)
    op.alter_column(
        "project_files",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_files",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_files", "file_size_bytes", existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True
    )
    op.alter_column("generated_images", "prompt", existing_type=sa.TEXT(), nullable=True)
    op.create_unique_constraint(
        op.f("uq_provider_org_year_month"),
        "api_costs_monthly",
        ["provider", "organization_id", "year", "month"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_api_costs_monthly_provider_year_month"),
        "api_costs_monthly",
        ["provider", "year", "month"],
        unique=False,
    )
    # ### end Alembic commands ###
