"""add messages_archive table and is_summary column

Revision ID: e57e0e47507a
Revises: cddc3eaa7795
Create Date: 2025-10-11 17:21:25.383229

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e57e0e47507a"
down_revision: str | Sequence[str] | None = "cddc3eaa7795"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages_archive",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_message_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("original_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("summary_message_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_archive_conversation_id"), "messages_archive", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_messages_archive_id"), "messages_archive", ["id"], unique=False)
    op.create_index(
        op.f("ix_messages_archive_original_message_id"), "messages_archive", ["original_message_id"], unique=False
    )
    op.drop_index(op.f("ix_conversations_user_archived"), table_name="conversations")
    op.add_column("messages", sa.Column("is_summary", sa.Boolean(), nullable=True))
    op.drop_constraint(op.f("messages_conversation_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "conversations", ["conversation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_conversation_id_fkey"),
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("messages", "is_summary")
    op.create_index(op.f("ix_conversations_user_archived"), "conversations", ["user_id", "archived"], unique=False)
    op.drop_index(op.f("ix_messages_archive_original_message_id"), table_name="messages_archive")
    op.drop_index(op.f("ix_messages_archive_id"), table_name="messages_archive")
    op.drop_index(op.f("ix_messages_archive_conversation_id"), table_name="messages_archive")
    op.drop_table("messages_archive")
    # ### end Alembic commands ###
