"""Add title and tags fields to songs table

Revision ID: 67836ff70afb
Revises: 02794a7298bd
Create Date: 2025-09-16 15:55:37.953581

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "67836ff70afb"
down_revision: str | Sequence[str] | None = "02794a7298bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("songs", sa.Column("title", sa.String(length=500), nullable=True))
    op.add_column("songs", sa.Column("tags", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("songs", "tags")
    op.drop_column("songs", "title")
    # ### end Alembic commands ###
