"""create_equipment_table

Revision ID: d4a678986a16
Revises: 0femi2213rz5
Create Date: 2025-10-29 10:16:53.143328

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d4a678986a16"
down_revision: str | Sequence[str] | None = "0femi2213rz5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("software_tags", sa.String(length=1000), nullable=True),
        sa.Column("plugin_tags", sa.String(length=1000), nullable=True),
        sa.Column("manufacturer", sa.String(length=200), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("username", sa.String(length=200), nullable=True),
        sa.Column("password_encrypted", sa.Text(), nullable=True),
        sa.Column("license_management", sa.String(length=100), nullable=True),
        sa.Column("license_key_encrypted", sa.Text(), nullable=True),
        sa.Column("license_description", sa.Text(), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("price_encrypted", sa.Text(), nullable=True),
        sa.Column("system_requirements", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(op.f("ix_equipment_status"), "equipment", ["status"], unique=False)
    op.create_index(op.f("ix_equipment_type"), "equipment", ["type"], unique=False)
    op.create_index(op.f("ix_equipment_user_id"), "equipment", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_equipment_user_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_type"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_status"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_table("equipment")
    # ### end Alembic commands ###
