"""add_enhanced_prompt_and_style_fields_to_images

Revision ID: ee8edc060263
Revises: 5a095be007d5
Create Date: 2025-10-22 10:14:42.054957

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ee8edc060263"
down_revision: str | Sequence[str] | None = "5a095be007d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generated_images", sa.Column("enhanced_prompt", sa.Text(), nullable=True))
    op.add_column("generated_images", sa.Column("artistic_style", sa.String(length=50), nullable=True))
    op.add_column("generated_images", sa.Column("composition", sa.String(length=50), nullable=True))
    op.add_column("generated_images", sa.Column("lighting", sa.String(length=50), nullable=True))
    op.add_column("generated_images", sa.Column("color_palette", sa.String(length=50), nullable=True))
    op.add_column("generated_images", sa.Column("detail_level", sa.String(length=50), nullable=True))
    op.drop_constraint(op.f("uq_lyric_parsing_rule_name"), "lyric_parsing_rules", type_="unique")
    op.drop_constraint(op.f("uq_prompt_category_action"), "prompt_templates", type_="unique")
    op.drop_constraint(op.f("songs_task_id_key"), "songs", type_="unique")
    op.create_index(op.f("ix_songs_task_id"), "songs", ["task_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_songs_task_id"), table_name="songs")
    op.create_unique_constraint(op.f("songs_task_id_key"), "songs", ["task_id"], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(
        op.f("uq_prompt_category_action"),
        "prompt_templates",
        ["category", "action"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_lyric_parsing_rule_name"), "lyric_parsing_rules", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("generated_images", "detail_level")
    op.drop_column("generated_images", "color_palette")
    op.drop_column("generated_images", "lighting")
    op.drop_column("generated_images", "composition")
    op.drop_column("generated_images", "artistic_style")
    op.drop_column("generated_images", "enhanced_prompt")
    # ### end Alembic commands ###
